[package]
name = "kf"
version = "0.1.0"
edition = "2021"

[dependencies]
"rfd" = "0.14.1"
"rand" = "0.8"
"egui" = "0.28.0"
"eframe" = "0.28.1"
rand_chacha = "0.3.1"
egui_extras = { version = "*", features = ["all_loaders"] }
image = "0.25.1"
